#+OPTIONS: ^:{}

#+TITLE: CEOS API Document
#+AUTHOR: fanwenjie

* Overview
#+BEGIN_QUOTE
conwin embed os采用分时调度方法，它的目标是简化应用程序的编写，增强程序的可读性和可维护性。
#+END_QUOTE
#+BEGIN_QUOTE
ceos的基本元素为Task，过去编写程序时，每个模块都有一个loop，再把所有的loop放到主程序的loop中，所有的loop依次执行。使用ceos框架，
每个模块只需要继承Task类，override loop方法即可，在loop中执行本模块的逻辑功能。
#+END_QUOTE
#+BEGIN_QUOTE
*使用ceos的一些约定*
- 数据类型请采用typedef.h中的定义
- 代码中变量，函数的命名采用全小写加下划线方式，统一风格
- 模块内的while循环无阻塞且尽可能的短
- 模块和驱动程序之间采用函数直接调用的方式，但模块之间的操作尽量采用回调的方式以降低耦合度
#+END_QUOTE

* Conwin Embed Operaing System 
** Task
提供系统任务执行接口
具体参见：[[ceos_api.org][ceos系统API]]
** Task_timer
系统软件定时器，loop级别，非精准定时。
具体参见：[[ceos_api.org][ceos系统API]]
** Hard_timer
系统硬件定时器，硬件中断级别，精准定时。
具体参见：[[ceos_api.org][ceos系统API]]
** Queue
循环对列，提供以字节为单位的队列类型和以void *为单位的队列类型。
具体参见：[[ceos_api.org][ceos系统API]]
** List
通用链表操作，具体参见：[[ceos_api.org][ceos系统API]]
** JSON lib
TObject库，提供JSON对像操作方法，以及和字符串之间的相互转换。
具体参见：[[json_lib.org][JSON库使用方法]]
* File System and Simple Database
** loop
** File
** Dir

* Bus
总线协议参见：[[bus_protocol.org][丛文设备总线协议文档]]
bus分为master和slave，api参见：[[bus_api.org][bus驱动API]]
* Net
** Enthernet
   W5500有线网络驱动
** GPRS & 4G
** DHCP Client
** DNS Client
* Http Server
