#+OPTIONS: ^:{}

#+TITLE: CEOS API Document
#+AUTHOR: fanwenjie

* Overview
#+BEGIN_QUOTE
conwin embed os采用分时调度方法，它的目标是简化应用程序的编写，增强程序的可读性和可维护性。
#+END_QUOTE
#+BEGIN_QUOTE
ceos的基本元素为Task，过去编写程序时，每个模块都有一个loop，再把所有的loop放到主程序的loop中，所有的loop依次执行。使用ceos框架，
每个模块只需要继承Task类，override loop方法即可，在loop中执行本模块的逻辑功能。
#+END_QUOTE
#+BEGIN_QUOTE
*使用ceos的一些约定*
- 数据类型请采用typedef.h中的定义
- 代码中变量，函数的命名采用全小写加下划线方式，统一风格
- 模块内的while循环无阻塞且尽可能的短
- 模块和驱动程序之间采用函数直接调用的方式，但模块之间的操作尽量采用回调的方式以降低耦合度
#+END_QUOTE

* 1 Conwin Embed Operaing System 
** 1.1 Task
   系统基本对像，每一个需要loop的模块都应该继承Task类。
   - 类定义 task.h
   - 提供方法:
     #+BEGIN_SRC 
     i8 running();                       //判断Task是否运行
     void pause();                       //挂起Task运行
     void resume();                      //恢复Task运行
     u16 pid();                          //获取task id
     Task *parent();                     //获取Task的父类
     const char *name();                 //获取Task名称
     void push_timer(Task_timer *timer); //给Task增加timer(具体见1.2 Task_timer)
     
     #+END_SRC
   - 使用方法
     1) 继承Task，构造方法必须指定父类和名称
     2) 在setup方法中执行父类的setup方法，
     3) override loop方法
   - 使用示例
     
#+BEGIN_QUOTE
   #+BEGIN_SRC c++
   //类定义
   class Bus: public Task {
     private:
     public:
       Bus(Task *parent, const char *name);
       ~Bus();
     
       void setup();
       void loop();
   }

   //setup方法中执行父类的setup
   i8 Bus::setup() {
     Task::setup();
   }

   //override loop
   void Bus::loop() {
   
   }

   //类使用
   bus = new Bus(&panel_4008, "485-bus-master");
   #+END_SRC
#+END_QUOTE
   
** 1.2 Task_timer
   系统软件定时器，loop级别，非精准定时。

** 1.3 Hard_timer
   系统硬件定时器，硬件中断级别，精准定时。

** 1.4 Queue
   循环对像，提供以字节为单位的队列类型和以void *为单位的队列类型。
   
** 1.5 List
   链表

** 1.6 JSON lib
   JSON操作库，可以解析字符串为Json Ojbect，也可以创建Json Object，再序列化为字符串。

*** 6.1 json parser
    字符串解析为Json Object

*** 6.2 json object method
    Json对像操作方法，并序列化为字符串
  
* 2 File System and Simple Database

** 2.1 loop
** 2.2 File
** 2.3 Dir

* 3 Bus

** 3.1 Bus master
   总线主设备驱动

** 3.2 Bus slave
   总线从设备驱动
  
* 4 Net
** 4.1 Enthernet
   W5500有线网络驱动

** 4.2 GPRS & 4G
   
** 4.3 DHCP Client

** 4.4 DNS Client

* 5 Http Server
